pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/NiranjanSurve/DO_Practical05.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Q_5') {
                    script {
                        // Make sure Docker is available on the Jenkins agent
                        docker.build('nodejs-app', '.')
                    }
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Run the Docker container with proper port mapping
                    docker.image('nodejs-app').run('-p 3000:3000')
                }
            }
        }
    }
}
